### ISSUE TITLE
Feature request: Open the Tailwind docs with cmd+enter

### ISSUE THREAD

**Issue by saeedesmaili** [phuibonhoa/alfred-tailwind#2]
Thanks for sharing this useful workflow.

It would be nice to be able to open the tailwind docs with cmd+enter to view more in-depth information about the searched class.

**Comment by phuibonhoa** [comment]
Great suggestion, I'll look into it

**Comment by phuibonhoa** [comment]
@saeedesmaili - Just FYI just overhauled a lot of the backend to make maintenance and additions much easier.  I'll look at adding the shortcut to open the docs next.

**Comment by phuibonhoa** [comment]
@saeedesmaili The latest release includes this feature: https://github.com/phuibonhoa/alfred-tailwind/releases/tag/v1.1.1

Thanks for the suggestion.  If you find any issues with the feature, please feel free to add a comment here and reopen this issue.
